[project]
id = "lwswycdksrmputowfbwu"

[api]
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = [
  "http://localhost:5173/update-password",
  "http://localhost:5173/login",
  "https://neurolearn-one.vercel.app",
  "https://neurolearn-one.vercel.app/update-password",
  "https://neurolearn-one.vercel.app/login",
]
jwt_expiry = 3600

[auth.external.google]
enabled = false
