[api]
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
port = 54323

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://neurolearn-one.vercel.app"]
jwt_expiry = 3600

[auth.external.google]
enabled = false
